services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    contao_news.picker.news_provider:
        class: Contao\NewsBundle\Picker\NewsPickerProvider
        arguments:
            - '@knp_menu.factory'
            - '@router'
            - '@?translator'
            - '@security.helper'
        tags:
            - { name: contao.picker_provider, priority: 128 }

    Contao\NewsBundle\Routing\Content\NewsRouteProvider:
        arguments:
            - '@contao.framework'
            - '@Contao\CoreBundle\Routing\RouteFactory'
