<?php

declare(strict_types=1);

/*
 * This file is part of Contao.
 *
 * (c) Leo Feyer
 *
 * @license LGPL-3.0-or-later
 */

namespace Contao\CoreBundle\Routing\Page;

use Contao\PageModel;

/**
 * The UrlResolverInterface allows a page controller to generate its front end URL.
 * This is only useful to implement if the target URL cannot be generated by Symfony
 * routing (e.g. for an external redirect page).
 */
interface UrlResolverInterface
{
    /**
     * If the page URL is absolute (e.g. an external link), the method can
     * directly return a string. It can also return a new page model to generate
     * the URL for instead (e.g. an internal link), or it can return the existing
     * page model if that URL should be generated through Symfony routing.
     */
    public function resolvePageUrl(PageModel $pageModel): PageModel|string;
}
