services:
    _defaults:
        autoconfigure: true

    contao_newsletter.cron.purge_subscriptions:
        class: Contao\NewsletterBundle\Cron\PurgeSubscriptionsCron
        arguments:
            - '@contao.framework'
            - '@?monolog.logger.contao.cron'

    contao_newsletter.listener.member_activation_mail:
        class: Contao\NewsletterBundle\EventListener\MemberActivationMailListener
        arguments:
            - '@database_connection'
        tags:
            - kernel.event_listener

    contao_newsletter.listener.sitemap:
        class: Contao\NewsletterBundle\EventListener\SitemapListener
        arguments:
            - '@contao.framework'
            - '@security.helper'
            - '@contao.routing.content_url_generator'
        tags:
            - kernel.event_listener

    contao_newsletter.routing.newsletter_url_resolver:
        class: Contao\NewsletterBundle\Routing\NewsletterUrlResolver
        arguments:
            - '@translator'
