services:
    _defaults:
        autoconfigure: true
        public: true

    Contao\CoreBundle\Controller\Page\ErrorPageController:
        tags:
            - { name: contao.page, type: error_401 }
            - { name: contao.page, type: error_403 }
            - { name: contao.page, type: error_404 }
            - { name: monolog.logger, channel: contao }

    Contao\CoreBundle\Controller\Page\ForwardPageController:
        tags:
            - { name: contao.page }
            - { name: monolog.logger, channel: contao }

    Contao\CoreBundle\Controller\Page\LogoutPageController:
        arguments:
            - '@security.logout_url_generator'
        tags:
            - { name: contao.page }

    Contao\CoreBundle\Controller\Page\RedirectPageController:
        tags:
            - { name: contao.page }

    Contao\CoreBundle\Controller\Page\RegularPageController:
        tags:
            - { name: contao.page }

    Contao\CoreBundle\Controller\Page\RootPageController:
        tags:
            - { name: contao.page, contentComposition: false }
            - { name: monolog.logger, channel: contao }
